# Generated by Django 2.0.6 on 2018-06-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20180607_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='tittle',
            new_name='title',
        ),
    ]
